Update noggin schemas
fedora-infra/noggin-messages pull request #290
Opened 2023-01-16 11:13 UTC by ryanlerch

Adds a bunch of missing properties like summary, agent_name, __str__, and app_name that are needed for upcoming FMN work

Signed-off-by: Ryan Lerch <rlerch@redhat.com>

2023-01-16 11:22 UTC, nphilipp requested changes

2023-01-16 11:22 UTC, nphilipp commented on noggin_messages/__init__.py
> +    def __str__(self):
I think `__str__` shouldn't be a property.

2023-01-16 11:22 UTC, nphilipp commented on noggin_messages/__init__.py
> +    def __str__(self):
Same here.

2023-01-16 11:22 UTC, nphilipp commented on noggin_messages/tests/test_schemas.py
> +        assert msg.__str__ == msg.summary
This would become `assert str(msg) == msg.summary` then.

2023-01-16 11:22 UTC, nphilipp commented on noggin_messages/tests/test_schemas.py
> +        assert msg.__str__ == msg.summary
… and likewise.

2023-01-16 11:22 UTC, nphilipp commented on noggin_messages/tests/test_schemas.py
> +        assert msg.__str__ == (
Here, too 🙂

2023-01-16 11:22 UTC, nphilipp commented on noggin_messages/tests/test_schemas.py
> +        assert msg2.__str__ == (
… and here.

2023-01-18 14:07 UTC, abompard requested changes

2023-01-18 14:07 UTC, abompard commented on noggin_messages/__init__.py
> +        return user_avatar_url(self.agent_name)
That's basically what the default `agent_avatar` property does, so you don't need to subclass it here.

2023-01-18 14:07 UTC, abompard commented on noggin_messages/__init__.py
> +        return "fas"
This is supposed to be human-readable, so you can set "FAS" here, or "Account System"

2023-03-28 15:53 UTC, merged